apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidate-api
  labels:
    app: candidate-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candidate-api
  template:
    metadata:
      labels:
        app: candidate-api
    spec:
      containers:
        - name: candidate-api
          image: ghcr.io/udaysingh007/sre-take-home:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: candidate-api-env
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: tmp
          emptyDir: {}
