apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: candidate-api
  labels:
    app: candidate-api
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: candidate-api
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
