apiVersion: v1
kind: Service
metadata:
  name: candidate-api
  labels:
    app: candidate-api
spec:
  selector:
    app: candidate-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
