apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - ingress.yaml
  - middleware.yaml

configMapGenerator:
  - name: candidate-api-env
    literals:
      - ASPNETCORE_ENVIRONMENT=Development

images:
  - name: ghcr.io/udaysingh007/sre-take-home
    newTag: "1.2.0"
